example_project/demo/urls.py
'''Demo URLs'''
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from demo.views import MyListView

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='demo/introduction.html'), name='introduction'),
    url(r'^kitchen-sink/$', 'demo.views.kitchen_sink', name='kitchen_sink'),
    url(r'^list-view/$', MyListView.as_view(), name='list_view'),
    url(r'^forms/$', 'demo.views.test_form', name='forms'),
    url(r'^400/$', 'demo.views.error', {'code': 400}, name='400'),
    url(r'^403/$', 'demo.views.error', {'code': 403}, name='403'),
    url(r'^404/$', 'demo.views.error', {'code': 404}, name='404'),
    url(r'^500/$', 'demo.views.error', {'code': 500}, name='500'),
    url(r'^no-access/$', 'demo.views.no_access', name='no_access'),
)

example_project/example_project/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^', include('demo.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'nuit/generic/login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
)

example_project/demo/models.py
from django.db import models

class Publisher(models.Model):
    #title = models.CharField(max_length=30, choices=(('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr')), default='Mr')
    #first_name = models.CharField(max_length=30)
    #last_name = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()
    sleazy = models.BooleanField()

    def __unicode__(self):
        return self.name

class Author(models.Model):
    salutation = models.CharField(max_length=10)
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __unicode__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()

example_project/demo/forms.py
from django.forms import ModelForm, ValidationError, CharField
from .models import Publisher

class PublisherForm(ModelForm):
    name = CharField(help_text='The name of the publisher')
    class Meta:
        model = Publisher
        fields = ('name', 'address', 'city', 'state_province', 'country', 'website', 'sleazy')
    def clean(self):
        raise ValidationError('Something went wrong')

example_project/demo/views.py
from django.shortcuts import render
from nuit.views import SearchableListView
from .models import Publisher
from .forms import PublisherForm
from django.contrib import messages
from django.contrib.auth.decorators import permission_required

class MyListView(SearchableListView):
    model = Publisher
    template_name = 'demo/list_view.html'
    paginate_by = 15
    search_fields = ('name', ('address', 'iexact'))

def kitchen_sink(request):
    messages.set_level(request, messages.DEBUG)
    messages.add_message(request, messages.DEBUG, 'Debug Message')
    messages.add_message(request, messages.INFO, 'Info Message')
    messages.add_message(request, messages.SUCCESS, 'Success Message')
    messages.add_message(request, messages.WARNING, 'Warning Message')
    messages.add_message(request, messages.ERROR, 'Error Message')
    return render(request, 'demo/kitchensink.html', {})

def test_form(request):
    if request.method == 'POST':
        form = PublisherForm(request.POST)
        if form.is_valid():
            pass
    else:
        form = PublisherForm()
    return render(request, 'demo/forms.html', {'form': form, 'data': 'Data'})

def error(request, code='400'):
    return render(request, 'nuit/generic/%s.html' % code, {}, status=code)

@permission_required('does.not.exist')
def no_access(request):
    return 'Go Away'

example_project/demo/templates/demo/base.html
{% extend 'nuit/base.html' topbar=True leftmenu=True breadcrumbs=True show_user_info=True show_search=True search_view='kitchen_sink' %}

{% block breadcrumbs %}
    {% menu_item link='/' name='Demo Project' %}
{% endblock %}

{% block left_menu %}

{% app_menu "Demo Project" can_collapse=True %}

    {% menu_item link='/' name='Introduction' %}

    {% url 'kitchen_sink' as kitchen_sink_url %}
    {% menu_item link=kitchen_sink_url name='Kitchen Sink' id='sink' %}

    {% url 'list_view' as list_view %}
    {% menu_item link=list_view name='Searchable List View' id='list_view' %}

    {% url 'forms' as forms %}
    {% menu_item link=forms name='Forms' id='forms' %}

{% end_app_menu %}

{% menu_section 'Collapsing' can_collapse=True %}
    <p>I can collapse!</p>
{% end_menu_section %}

{% menu_section 'Automatic Link Hiding' is_list=True can_collapse=True %}
    {% menu_item link='no_access' name="I'm Invisible" %}
    {% menu_item link='no_access' always_display=True name="I'm not invisible." %}
{% end_menu_section %}

{% endblock %}

{% block top_bar_menu %}
    {% menu_item link='/' name='Test Link' %}
{% endblock top_bar_menu %}

{% block top_bar_right_menu %}
    {% menu_item link='/' name='Test Right Link' %}
{% endblock top_bar_right_menu %}

{% block user_info_menu %}
    {% menu_item link='/' name='Test User Info Link' %}
{% endblock user_info_menu %}

example_project/demo/templates/demo/forms.html
{% extend 'demo/base.html' rightmenu=True %}

{% block title %}Forms{% endblock %}

{% block breadcrumbs %}
{{block.super}}
{% menu_item name='Forms' link=request.path %}
{% endblock %}

{% block content %}

    {% set_active_menu 'forms' %}

    <h1>Forms</h1>

    <form method='post' action=''>
        {% foundation_form form %}
            name {'medium': 4,}; address {'prefix': data, 'prefix_medium': 6, 'prefix_large': 0}
            city; state_province; country {'postfix': 'Post', 'postfix_small': 6, 'postfix_medium': 0}
            website {'prefix': 'Pre'}; sleazy {'medium': 2, 'switch': True, 'switch_class': 'round small'}
        {% end_foundation_form %}
        <button class='button small-only-expand'>Submit</button>
    </form>

    <h2>Manual Form</h2>

    <form>
        <div class='row'>
            <div class='medium-3 columns'>
                <label class='medium-right medium-inline' for='foo'>Foo</label>
            </div>
            <div class='medium-9 columns'>
                <input type='text' name='foo' id='foo' />
            </div>
        </div>
    </form>

{% endblock %}

{% block right_menu %}

{% menu_section "Bob" %}

    <form method='post' action=''>
        <button class='button'>Submit</button>
    </form>

{% end_menu_section %}

{% endblock %}

example_project/demo/templates/demo/introduction.html
{% extend 'demo/base.html' rightmenu=True app_logo='Nuit <span class="label radius">BETA</span>' %}

{% block right_menu %}

    {% menu_section is_list=True title='Links!' %}
        {% menu_item always_display=True link='#' name='Bob' %}
        {% menu_item always_display=True link='#' name='Ben' %}
        {% menu_item always_display=True link='#' name='Bop' %}
    {% end_menu_section %}

    {% menu_section title='Other Stuff' %}
        <p>This is some other stuff.</p>
    {% end_menu_section %}

{% endblock %}

{% block title %}Introduction{% endblock %}

{% block scripts %}

    <script type='text/javascript'>

    $(document).ready(function() {
        $('#confirmation').click(function() {
            nuit.confirmation_box();
        });
    });

    </script>

{% endblock scripts %}

{% block content %}

    {% set_active_menu 'introduction' %}

    <h1>Introduction</h1>

    <p>This demo project is designed to demonstrate the UI capabilities of Nuit.</p>

<dl class="tabs" data-tab data-options="deep_linking:true;scroll_to_content: false">
  <dd class="active"><a href="#panel1">Tab 1</a></dd>
  <dd><a href="#panel2">Tab 2</a></dd>
  <dd><a href="#panel3">Tab 3</a></dd>
  <dd><a href="#panel4">Tab 4</a></dd>
</dl>
<div class="tabs-content">
  <div class="content active" id="panel1">
    <p>This is the first panel of the basic tab example. This is the first panel of the basic tab example.</p>
  </div>
  <div class="content" id="panel2">
    <p>This is the second panel of the basic tab example. This is the second panel of   the basic tab example.</p>
  </div>
  <div class="content" id="panel3">
    <p>This is the third panel of the basic tab example. This is the third panel of the basic tab example.</p>
  </div>
  <div class="content" id="panel4">
    <p>This is the fourth panel of the basic tab example. This is the fourth panel of   the basic tab example.</p>
  </div>
</div>

    <p><a href='#' id='confirmation'>Click me!</a></p>
    <p><a href='#' data-reveal-id='other-stuff-2'>Click me!</a></p>


    <section class="right-menu-reveal reveal-modal" data-reveal="" id="other-stuff-2">
                <div>
                <h5>Other Stuff</h5>
                <div class="side-content">


        <p>This is some other stuff.</p>


                </div>
                </div>
                <hr>
            </section>



{% endblock %}

example_project/demo/templates/demo/kitchensink.html
{% extend 'demo/base.html' rightmenu=True %}

{% block title %}Kitchen Sink{% endblock %}

{% block breadcrumbs %}
    {{block.super}}
    {% url 'kitchen_sink' as kitchen_sink_url %}
    {% menu_item link=kitchen_sink_url name='Kitchen Sink' %}
{% endblock %}

{% block content %}

{% set_active_menu 'sink' %}

<h1>Kitchen Sink</h1>

<p>This page includes all the different elements currently designed to work with Nuit, so we can ensure that they all work happily together. See Foundation's <a href='http://foundation.zurb.com/docs/components/kitchen_sink.html'>documentation</a> for more detail and options - but if they're not listed here, they haven't yet been tested with Nuit.</p>

<h2>Typography</h2>

<p>This is just a sample of each style of typography available, to ensure that the Nuit stylings are suitable. See Foundation's <a href='http://foundation.zurb.com/docs/components/typography.html'>Typography</a> documentation for more detail and options.</p>

<h3>Headers</h3>

<p>All available header styles. Usually, only one <code>&lt;h1&gt;</code> should be used per page.</p>

<h1>h1. A very large header.</h1>
<h2>h2. A large header.</h2>
<h3>h3. A medium header.</h3>
<h4>h4. A small header.</h4>
<h5>h5. A very small header.</h5>
<h6>h6. A tiny header.</h6>

<h3>Lists</h3>

<ol>
    <li>An ordered list</li>
    <li>Should be used</li>
    <li>When you have</li>
    <li>A number of items</li>
    <li>That need to be ordered!</li>
    <li>You can
        <ol>
            <li>Nest them</li>
            <li>Too.</li>
        </ol>
    </li>
</ol>

<ul>
    <li>An unordered list</li>
    <li>Should be used</li>
    <li>When the order of</li>
    <li>The items doesn't matter.</li>
</ul>

<dl>
    <dt>Definition Lists</dt>
    <dd>Can be used to define items in a glossary, or provide a list of key-value pairs.</dd>
</dl>

<h3>Blockquotes</h3>

<blockquote>Those people who think they know everything are a great annoyance to those of us who do.<cite>Isaac Asimov</cite></blockquote>

<h2>Loaders</h2>

{% include 'nuit/includes/loader.html' with size=16 %}
{% include 'nuit/includes/loader.html' with size=32 %}
{% include 'nuit/includes/loader.html' with size=48 %}
{% include 'nuit/includes/loader.html' with size=64 %}
{% include 'nuit/includes/loader.html' with size=80 %}
{% include 'nuit/includes/loader.html' with size=96 %}

<h2>Tabs</h2>

<dl class="tabs" data-tab data-options="deep_linking:true">
  <dd class="active"><a href="#panel1">Tab 1</a></dd>
  <dd><a href="#panel2">Tab 2</a></dd>
  <dd><a href="#panel3">Tab 3</a></dd>
  <dd><a href="#panel4">Tab 4</a></dd>
</dl>
<div class="tabs-content">
  <div class="content active" id="panel1">
    <p>This is the first panel of the basic tab example. This is the first panel of the basic tab example.</p>
  </div>
  <div class="content" id="panel2">
    <p>This is the second panel of the basic tab example. This is the second panel of   the basic tab example.</p>
  </div>
  <div class="content" id="panel3">
    <p>This is the third panel of the basic tab example. This is the third panel of the basic tab example.</p>
  </div>
  <div class="content" id="panel4">
    <p>This is the fourth panel of the basic tab example. This is the fourth panel of   the basic tab example.</p>
  </div>
</div>

<h2>Tables</h2>

<p>Standard table, not responsive:</p>

<table>
  <thead>
    <tr>
      <th width='200'>Table Header</th>
      <th>Table Header</th>
      <th width='150'>Table Header</th>
      <th width='150'>Table Header</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer content Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer Content Goes Here Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer Content Goes Here Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
  </tbody>
</table>

<p>Standard table, grouped responsive:</p>

<table class='grouped responsive medium-down headers-30'>
  <thead>
    <tr>
      <th width='200'>Table Header 1</th>
      <th>Table Header 2</th>
      <th width='150'>Table Header 3</th>
      <th width='150'>Table Header 4</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer content Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer Content Goes Here Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer Content Goes Here Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
  </tbody>
</table>

<p>Standard table, scroll responsive:</p>

<table class='scroll responsive medium-down'>
  <thead>
    <tr>
      <th width='200'>Table Header</th>
      <th>Table Header</th>
      <th width='150'>Table Header</th>
      <th width='150'>Table Header</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer content Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer Content Goes Here Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
    <tr>
      <td>Content Goes Here</td>
      <td>This is longer Content Goes Here Donec id elit non mi porta gravida at eget metus.</td>
      <td>Content Goes Here</td>
      <td>Content Goes Here</td>
    </tr>
  </tbody>
</table>

<h2>Key/Value Pairs</h2>


<ul class='small-block-grid-1 medium-block-grid-3 large-block-grid-4 key-value'>
    <li>
        <span class='key'>One Key</span>
        <span class='value'><a href='#'>Linked Value</a></span>
    </li>
    <li>
        <span class='key'>Two Key</span>
        <span class='value'>Simple Value</span>
    </il>
    <li>
        <span class='key'>Dimensions</span>
        <span class='value'>100mm x 200mm</span>
    </li>
    <li>
        <span class='key'>Weight</span>
        <span class='value'>20kg</span>
    </li>
</ul>

{% endblock %}

{% block left_menu %}

  {{block.super}}

  {% menu_section title='Table' %}
    <table>
      <tr>
        <td>Full width tables</td>
      </tr>
    </table>
  {% end_menu_section %}

{% endblock %}

{% block right_menu %}

    {% menu_section 'Everything but the kitchen sink&hellip;' %}
    <p>A phrase originating from World War II, meaning to take or use almost everything.</p>
    {% end_menu_section %}

    {% menu_section link_name='Definition Lists' %}
    <dl>
        <dt>Definition Lists&hellip;</dt>
        <dd>&hellip;have specific styling when used in the right menu.</dd>
    </dl>
    {% end_menu_section %}

    {% menu_section is_list=True %}
        {% menu_item name='A Link' link='#' always_display=True %}
        {% menu_item name='Add a message' link="javascript:nuit.add_message('info', 'A new message!');" always_display=True %}
    {% end_menu_section %}

    {% menu_section is_list=True title='Key (Nodes)' %}

      <li class='button-bar'>
        <ul class='button-group radius right' id='fully-failed-button-group'>
          <li><a href='#' class='tiny button' data-value='show'><i class='fi fi-check tip-left'></i></a></li>
          <li><a href='#' class='tiny alert button' data-value='hide'><i class='fi fi-x tip-left'></i></a></li>
        </ul>
        Fully Failed
      </li>

      <li class='button-bar'>
        <ul class='button-group radius right'>
          <li><a href='#' class='tiny alert button'><i class='fi fi-check tip-left'></i></a></li>
          <li><a href='#' class='tiny button'><i class='fi fi-x tip-left'></i></a></li>
        </ul>
        Partially Failed
      </li>

      <li class='button-bar'>
        <ul class='button-group radius right'>
          <li><a href='#' class='tiny alert button'><i class='fi fi-check tip-left'></i></a></li>
          <li><a href='#' class='tiny button'><i class='fi fi-x tip-left'></i></a></li>
        </ul>
        Not Failed
      </li>

    {% end_menu_section %}

    {% menu_section is_list=True title='Key (Edges: Failure Types)' %}

      <li class='button-bar'>
        <ul class='button-group radius right' id='asset-link-types'>
          <li><a href='#' class='tiny button' data-value='show'><i class='fi fi-check tip-left'></i></a></li>
          <li><a href='#' class='tiny alert button' data-value='hide'><i class='fi fi-x tip-left'></i></a></li>
          <li><a href='#' class='tiny button' data-value='collapse'><i class='fi fi-arrows-compress tip-left'></i></a></li>
        </ul>
        Asset
      </li>

      <li class='button-bar'>
        <ul class='button-group radius right'>
          <li><a href='#' class='tiny alert button'><i class='fi fi-check tip-left'></i></a></li>
          <li><a href='#' class='tiny button'><i class='fi fi-x tip-left'></i></a></li>
          <li><a href='#' class='tiny button'><i class='fi fi-arrows-compress tip-left'></i></a></li>
        </ul>
        Management Network
      </li>

      <li class='button-bar'>
        <ul class='button-group radius right'>
          <li><a href='#' class='tiny alert button'><i class='fi fi-check tip-left'></i></a></li>
          <li><a href='#' class='tiny button'><i class='fi fi-x tip-left'></i></a></li>
          <li><a href='#' class='tiny button'><i class='fi fi-arrows-compress tip-left'></i></a></li>
        </ul>
        Power
      </li>

    {% end_menu_section %}

    {% menu_section title='Table' %}
    <table>
      <tr>
        <td>Full width tables</td>
      </tr>
    </table>
    {% end_menu_section %}

    {% menu_section title='List' %}
    <ol>
      <li>One</li>
      <li>Two</li>
      <li>Three is the magic number (like the song)</li>
      <li>Four is one too many</li>
    </ol>
    {% end_menu_section %}

{% endblock %}

example_project/demo/templates/demo/list_view.html
{% extend 'nuit/generic/list.html' base='demo/base.html' rightmenu=False topbar=True leftmenu=True rightmenu=True search_verb='Filter' breadcrumbs=True %}

{% block title %}Publishers{% endblock %}

{% block breadcrumbs %}
{{block.super}}
{% menu_item name='List View' link=request.path %}
{% endblock %}

{% block content %}
{{block.super}}
{% set_active_menu 'list_view' %}
{% endblock %}

example_project/demo/templates/demo/publisher_form.html
{% load nuit %}
{% extend 'demo/publisher_list.html' %}

{% block title %}Publisher Form{% endblock %}

{% block breadcrumbs %}
{{block.super}}
{% url 'publisher_form' as publisher_url %}
{% menu_item name='New' link=publisher_url %}
{% endblock %}

{% block content %}

    <h1>Publisher Form</h1>
    
    <form method='post' action=''>
        {% foundation_form form %}
            name {'medium': 4,}; address {'prefix': 'Bob', 'prefix_medium': 6, 'prefix_large': 0}
            city; state_province; country {'postfix': 'Europe', 'postfix_small': 6, 'postfix_medium': 0}
            website {'prefix': 'http://'}
        {% end_foundation_form %}
        <button class='button'>Submit</button>
    </form>

{% endblock %}

{% block right_menu %}

{% menu_section "Bob" %}

    <form method='post' action=''>
        {% foundation_form form collapse_container=True %}
            name {'show_label': False}
        {% end_foundation_form %}
        <button class='button'>Submit</button>
    </form>

{% end_menu_section %}

{% endblock %}

example_project/demo/templates/demo/publisher_list.html
{% load nuit %}
{% extend 'nuit/generic/list.html' base='demo/base.html' rightmenu=False topbar=True leftmenu=True rightmenu=True search_verb='Filter' breadcrumbs=True %}

{% block title %}Publishers{% endblock %}

{% block breadcrumbs %}
{{block.super}}
{% menu_item name='Publishers' link='/publishers/' %}
{% endblock %}

{% block content %}
{{block.super}}
{% set_active_menu "infmis2" %}
{% endblock %}

{% block right_menu %}

{% menu_section is_list=True %}
{% url 'publishers_add' as publisher_form %}
{% menu_item name='Add New Publisher' link=publisher_form %}
{% end_menu_section %}

{{block.super}}

{% endblock %}

example_project/demo/templates/demo/table.html
{% extend 'demo/base.html'  %}

{% block content %}

<table class='responsive grouped headers-30 medium-down'>

    <thead>
        <tr>
            <th>Site</th>
            <th>Host</th>
            <th>Device</th>
            <th>Interface</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>

        <tr>
            <td data-title='Site'>ts (Test spoke)</td>
            <td><a href="/assetchicken/asset/4720/">ittsrt01</a></td>
            <td>Cisco 1801W-AG-E/K9</td>
            <td>ATM0 (ADSLoPOTS)</td>
            <td>
                <button data-reveal-id="confirm" class="button tiny bounce" data-port="38347" data-disable-url="/rackchicken/api/v1/port/38347/disable/" data-enable-url="/rackchicken/api/v1/port/38347/enable/" style='margin: 0;'>
                    Bounce
                </button>
            </td>
        </tr>

        <tr>
            <td>ts (Test spoke)</td>
            <td><a href="/assetchicken/asset/1700/">ittsrt02</a></td>
            <td>Cisco 1801W-AG-E/K9 ag sdkgs dgskdj ngjksd njksdn gkjn gkjsdbng jksd kj gasklj fhsdkjbsg </td>
            <td>ATM0 (ADSLoPOTS)</td>
            <td>
                <button data-reveal-id="confirm" class="button tiny bounce success" data-port="114742" data-disable-url="/rackchicken/api/v1/port/114742/disable/" data-enable-url="/rackchicken/api/v1/port/114742/enable/" style="display: inline-block;margin: 0">Success</button>
            </td>
        </tr>

    </tbody>

</table>

{% endblock %}